export const panelDiscussion = {
  theme: 'AI Agents: Transforming Industry, Academia, and the Future of Intelligent Work',
  date: 'Friday, 24 July 2026',
  time: '9:30 AM – 10:30 AM (IST)',
  moderator: {
    name: 'Dr. Yash Chawla',
    role: 'Moderator',
    designation: 'Founder & Head, CRAFT',
    affiliations: [
      'Faculty of Management, Wroclaw University of Science and Technology, Poland',
    ],
    image: '/images/keynote-speakers/portrait-uniform/yash-chawla.png',
    imageClassName: 'object-contain object-bottom',
  },
  panelists: [
    {
      name: 'Mr. Yogesh Sharma',
      role: 'Distinguished Panelist',
      designation: 'Co-Founder & Chairperson, Mamsys World',
      affiliations: [
        'Author, The Slim Elephant',
        'AI Strategist & Global Technology Leader',
      ],
      image: '/images/panel-discussion/yogesh-sharma-user-transparent.png',
      imageClassName: 'object-contain object-bottom',
    },
    {
      name: 'Mr. Vikram Singh',
      role: 'Distinguished Panelist',
      designation: 'Delivery Coordinator',
      affiliations: [
        'Compliance & AI Governance Specialist',
        'Tata Consultancy Services (deployed at Nationwide)',
      ],
      image: '/images/panel-discussion/vikram-singh-transparent.png',
      imageClassName: 'object-contain object-bottom',
    },
    {
      name: 'Mr. Sarvesh Kumar Gupta',
      role: 'Distinguished Panelist',
      designation: 'Consulting Member of Technical Staff (Senior Principal Engineer)',
      affiliations: ['Oracle'],
      image: '/images/panel-discussion/sarvesh-kumar-gupta-transparent.png',
      imageClassName: 'object-contain object-bottom',
    },
    {
      name: 'Dr. Ishu Anand Jaiswal',
      role: 'Distinguished Panelist',
      designation: 'Senior Engineering Leader, Intuit (Ex-Apple)',
      affiliations: ['Author', 'Senior IEEE Member'],
      image: '/images/panel-discussion/ishu-anand-jaiswal-transparent.png',
      imageClassName: 'object-contain object-bottom',
    },
    {
      name: 'Mr. Ankur Khare',
      role: 'Distinguished Panelist',
      designation: 'AI Innovation Advisor',
      affiliations: ['SAP'],
      image: '/images/panel-discussion/ankur-khare-transparent.png',
      imageClassName: 'object-contain object-bottom',
    },
    {
      name: 'Mr. Ashutosh Chandra Jha',
      role: 'Distinguished Panelist',
      designation: 'Network Security Engineer',
      affiliations: ['New York University, USA'],
      image: '/images/panel-discussion/ashutosh-chandra-jha-transparent.png',
      imageClassName: 'object-contain object-bottom',
    },
    {
      name: 'Mr. Prakhar Mittal',
      role: 'Distinguished Panelist',
      designation: 'Digital Transformation Leader, AtriCure, USA',
      affiliations: ['Product Management Leader', 'IIM Ahmedabad Alumnus'],
      image: '/images/panel-discussion/prakhar-mittal-transparent.png',
      imageClassName: 'object-contain object-bottom',
    },
    {
      name: 'Justin Rajakumar Maria Thason',
      role: 'Distinguished Panelist',
      designation: 'Sr. Technical DevOps Lead Architect (Manager)',
      affiliations: ['CareFirst BlueCross BlueShield'],
      image: '/images/panel-discussion/justin-rajakumar-maria-thason-transparent.png',
      imageClassName: 'object-contain object-bottom',
    },
  ],
};
