export const speakerRoster = [
  {
    order: '01',
    name: 'Shri Ashok Gupta',
    role: 'Chief Guest',
    designation: 'Director, STPI & CEO, STPI Apiary',
    affiliations: ['Gurugram, Haryana'],
    image: '/images/keynote-speakers/portrait-uniform/ashok-gupta-user-transparent.png',
  },
  {
    order: '02',
    name: 'Prof. (Dr.) Sri Niwas Singh',
    role: 'Guest of Honour',
    designation: 'Director',
    affiliations: [
      'Atal Bihari Vajpayee Indian Institute of Information Technology and Management (ABV-IIITM), Gwalior, India',
    ],
    image: '/images/keynote-speakers/portrait-uniform/sri-niwas-singh.png',
    bio: [
      'Prof. S. N. Singh is Director of the Atal Bihari Vajpayee Indian Institute of Information Technology and Management, Gwalior, Madhya Pradesh, India. He earned his M.Tech. and Ph.D. in Electrical Engineering from the Indian Institute of Technology Kanpur in 1989 and 1995, respectively.',
      'He began his professional career with the Uttar Pradesh State Electricity Board, serving as Assistant Engineer from 1988 to 1996. He then worked as Assistant Professor at the University of Roorkee, now IIT Roorkee, from 1996 to 2000, and at the Asian Institute of Technology, Bangkok, Thailand, from 2001 to 2002, before joining IIT Kanpur as Associate Professor. He served as Vice-Chancellor of Madan Mohan Malaviya University of Technology, Gorakhpur, from April 2017 to July 2020.',
      'Prof. Singh served as Chairman of the IEEE Uttar Pradesh Section in 2013 and 2014, IEEE Region 10 Conference and Technical Seminar Coordinator from 2015 to 2018, and IEEE Region 10 Vice-Chair for Technical Activities from 2019 to 2020.',
      'His research interests include power system restructuring, FACTS, power system optimization and control, security analysis, and wind power. He has published extensively in national journals and conference proceedings and has supervised 42 Ph.D. scholars, with nine more in progress. He has written 33 book chapters, edited 13 books, and authored two textbooks: Electrical Power Generation, Transmission and Distribution and Basic Electrical Engineering, published by PHI India. He has completed approximately three dozen technical projects in India and abroad. His two NPTEL video lecture series on HVDC Transmission and Power System Operation and Control are very popular.',
    ],
    achievements: [
      'Fellow of IEEE (USA), INAE, IET (UK), IE(I), IETE, AvH, AAIA, and AIIA',
      'C.B.I.P. Young Engineer Award (1996)',
      'Khosla Research Award (Commendation), University of Roorkee (1998)',
      'INAE Young Engineer Award (2000)',
      'Khosla Research Award (Gold), University of Roorkee (2000)',
      'Humboldt Research Fellowship, Germany (2005 and 2007)',
      '21st Century Award for Achievement, IBC Cambridge, England (2007)',
      'Otto Mønsteds Fond Award, Denmark (2009–2010)',
      'Three Ph.D. theses received the POSOCO Power System Award (2012)',
      'IEEE Educational Activities Board Meritorious Achievement Award, first Asian recipient (2013)',
      'Emerald Literati Network Award for Excellence, Emerald Publications, UK (2015)',
      'INAE Outstanding Teacher Award (2016)',
      'IEEE Region 10 Outstanding Volunteer Award (2016)',
      'IEEE Distinguished Lecturer, PES and IAS (2019–2021)',
      'NPSC Academic Excellence Award (2020)',
      'IEEE IAS Outstanding Educator/Mentor Award (2021)',
    ],
  },
  {
    order: '03',
    name: 'Dr. Pankaj Kumar Rawat',
    role: 'Guest of Honour / Keynote Speaker',
    designation: 'Scientist E',
    affiliations: ['ANRF'],
    image: '/images/keynote-speakers/portrait-uniform/pankaj-kumar-rawat.png',
    bio: [
      'Dr. Pankaj Rawat is currently serving the Science and Engineering Research Board (SERB) as Scientist-D. He has more than five years of professional experience in scientific R&D management. In his current role, he is the program officer for Core Research Grant (CRG) in Civil, Mechanical, Materials Engineering and related areas, Uchhatar Avishkar Yojana (UAY), National Science Chair (NSC), and Accelerate Vigyan (AV).',
      'Prior to his current role, he was a postdoctoral researcher at Yonsei University, Seoul, South Korea. He earned his M.Sc. in Physics from Kumaun University, Nainital, and his M.Tech. and Ph.D. in Materials Science and Engineering from the Indian Institute of Technology Kharagpur. He has published several research papers on thermoelectric materials in internationally reputed journals from ACS, RSC, IOP, Wiley, and Elsevier.',
      'Dr. Rawat is a recipient of awards including the Brain Korea 21 Postdoctoral Fellowship, DST-INSPIRE Faculty Award, and Japan-Asia Youth Exchange Program in Science.',
    ],
  },
  {
    order: '04',
    name: 'Dr. Pramod Kumar Prasad',
    role: 'Guest of Honour / Keynote Speaker',
    designation: 'Scientist E',
    affiliations: ['ANRF'],
    image: '/images/keynote-speakers/portrait-uniform/pramod-kumar-prasad.png',
    bio: [
      'Dr. Pramod Kumar Prasad is working as Scientist-D at the Science and Engineering Research Board (SERB), a statutory body of the Department of Science and Technology, Government of India. He was awarded a Ph.D. in Biotechnology and Bioinformatics from North-Eastern Hill University (a Central University), Shillong, Meghalaya. He is presently working as Program Officer for the implementation of Young Scientist - Life Sciences (YSS, ECRA, SRG, and NPDF), SERB-STAR, SERB-DIA, SERB-TETRA, and PAC-Organismal and Evolutionary Biology - Animal Sciences. Prior to joining SERB, he was involved in implementing the Internship and Faculty Award components of the Innovation in Science Pursuit for Inspired Research (INSPIRE) program of DST.',
      'His research covers the fields of Molecular Biology, Parasitology, and Bioinformatics. His Ph.D. work provided PCR-based diagnostic markers for species discrimination of zoonotic trematode parasites, supporting accurate diagnosis and the development of novel therapeutic and preventive strategies. He has filed a national patent for this work. It also resulted in 18 research papers in high-impact international and national journals and 42 DNA sequences in GenBank.',
    ],
  },
  {
    order: '05',
    name: 'Paulina Muszyńska',
    role: 'Keynote Speaker',
    designation: 'Head of Development Projects Department',
    affiliations: [
      'Wrocław Agglomeration Development Agency, Poland',
      'Head of Startup Wrocław | Chief Ecosystem Officer, Startup Ecosystem Strategist | Women in Tech Advocate',
    ],
    image: '/images/keynote-speakers/portrait-uniform/paulina-muszynska.png',
    bio: [
      'Paulina Muszyńska is an experienced innovation and startup ecosystem leader focused on building environments where entrepreneurship, technology, and collaboration become practical drivers of regional growth. For more than 10 years, she has worked across project development, event management, public relations, and ecosystem-building, designing and leading national and international initiatives that connect business, technology, academia, public institutions, and startup communities.',
      'As Head of the Development Projects Department at the Wrocław Agglomeration Development Agency and Head of Startup Wrocław, she plays a key role in strengthening the city’s innovation infrastructure. Her work focuses on connecting founders, investors, universities, local government, corporations, and technology partners in order to support entrepreneurship, accelerate business cooperation, and position Wrocław as one of Central Europe’s most dynamic startup and technology hubs.',
      'Her mission is to build a fast-moving, open, and globally connected startup ecosystem while keeping people, trust, and community at the center of innovation. Since January 2026, she has also served as Chairwoman of the Foundation Council at Startup Poland, where she supports efforts to make startup creation and scaling in Poland more attractive, accessible, and economically viable.',
    ],
  },
  {
    order: '06',
    name: 'Shri Akash Takyar',
    role: 'Keynote Speaker',
    designation: 'Founder and CEO',
    affiliations: ['LeewayHertz, USA'],
    image: '/images/keynote-speakers/portrait-uniform/akash-takyar.png',
    bio: [
      'Akash Takyar is a serial technology entrepreneur, enterprise AI leader, investor, and technical architect with deep experience building scalable digital platforms for global organizations. He is the Founder and CEO of LeewayHertz, recently acquired by NASDAQ-listed The Hackett Group, where he now serves as Executive Vice President of the AI Implementation Group.',
      'Over the past 15+ years, Akash has architected and delivered more than 100 enterprise platforms across AI, cloud, mobile, IoT, and automation, many of which are used by millions of people worldwide. His work has supported leading enterprises, including Fortune 500 companies such as Siemens, 3M, P&G, and the US Army.',
      'Akash is a member of the Forbes Technology Council and serves on several advisory boards. He also founded the world’s first smart chai-making robot, later acquired by a leading tea manufacturer. A recipient of the Indira Gandhi Priyadarshini Award, Akash brings practical insight into building and scaling enterprise-grade GenAI applications.',
    ],
  },
  {
    order: '07',
    name: 'Dr. Ankit Agrawal',
    role: 'Keynote Speaker',
    designation: 'Research Professor, Department of ECE',
    affiliations: ['Northwestern University, USA'],
    image: '/images/keynote-speakers/portrait-uniform/ankit-agrawal.png',
    bio: [
      'Dr. Ankit Agrawal (Ph.D. 2009, B.Tech. 2006) is a Research Professor in the Department of Electrical and Computer Engineering at Northwestern University, USA, an Affiliate Faculty at Northwestern International Institute for Nanotechnology as well as at Northwestern Paula M. Trienens Institute for Sustainability, and an honorary professor at Amity University, India. He specializes in interdisciplinary artificial intelligence (AI), machine learning (ML), and deep learning (DL) via high-performance data mining, to develop customized AI solutions for big data problems with real-world impact. A pioneer in materials informatics (AI for materials), his research has contributed to various scientific and engineering disciplines, such as materials science, healthcare, social media, and bioinformatics.',
      'He has co-authored 200+ peer-reviewed publications (100+ as first/last author) with 19,000+ citations (h-index: 50+), co-developed 20+ software, delivered 100+ invited/keynote/plenary talks at conferences, universities, and companies all over the world, been on program/organizing committees of 50+ conferences/workshops, and served as a PI/Co-PI/Co-I on 25+ projects with a combined budget of over $100 million, funded by various US federal agencies (e.g., NSF, DOE, AFOSR, NIST, DARPA, DLA, NIH) as well as industry (e.g., Toyota Motor Corporation Japan). He is also serving as the Editor-in-Chief of Computers, Materials & Continua, and as the Specialty Chief Editor of HPC Applications section of Frontiers in HPC.',
      'His AI/ML/DL expertise is routinely sought by industry, US federal agencies, international funding agencies, professional societies, academic publishers, etc. He is also regularly invited to speak about his work on interdisciplinary AI at conferences, workshops, panels, universities, companies, etc. He has received many honors and awards throughout his academic career, such as graduating department topper in CSE at IIT Roorkee, research excellence awards during his PhD at Iowa State University, and data science initiative awards and Hind Rattan Award while at Northwestern University. He has been featured in Stanford/Elsevier’s list of top 2% scientists, as well as named a ScholarGPS Top Scholar for being in top 0.5% of scholars worldwide in the fields of machine learning, deep learning, and informatics.',
    ],
  },
  {
    order: '08',
    name: 'Dr. Yash Chawla',
    role: 'Keynote Speaker',
    designation: 'Founder and Head of CRAFT',
    affiliations: [
      'Faculty of Management, Wroclaw University of Science and Technology, Poland',
    ],
    image: '/images/keynote-speakers/portrait-uniform/yash-chawla.png',
    bio: [
      'Dr. Yash Chawla is the Founder and Head of CRAFT, a collaboration-based laboratory and think tank at the Faculty of Management, Wroclaw University of Science and Technology. He also serves as the Deputy Head at the Department of Computational Social Science at Wrocław University of Science and Technology (WUST), Poland. He is also the Founder and CEO of SustematiQ, which builds societal impact and innovation solutions with people at the center.',
      'He holds a Ph.D. with distinction in Management Sciences and has a multidisciplinary background with two Master’s and two Bachelor’s degrees, encompassing Engineering, Computer Applications, and Business Administration. It enables him to work effectively at the confluence of technology, business strategy, and societal impact.',
      'With extensive academic and research experience, Dr. Chawla focuses on translating research insights into practical applications, particularly emphasizing sustainable development. He has extensive experience as a mentor at hackathons, including CASSINI Hackathons.',
    ],
  },
];
