export const conferenceGallery = [
  {
    id: 'stage-group-panel',
    src: '/images/conference-gallery/stage-group-panel.jpeg',
    section: 'Conference highlights',
    title: 'Delegates and invited guests on stage',
    alt: 'Delegates and invited guests gathered on stage during ICCISD-2026',
    featured: true,
  },
  {
    id: 'souvenir-release-stage',
    src: '/images/conference-gallery/souvenir-release-stage.jpeg',
    section: 'Conference highlights',
    title: 'Conference souvenir release',
    alt: 'Guests holding the ICCISD-2026 conference souvenir on stage',
    featured: true,
  },
  {
    id: 'lamp-lighting-01',
    src: '/images/conference-gallery/lamp-lighting-01.jpeg',
    section: 'Opening ceremony',
    title: 'Lighting of the ceremonial lamp',
    alt: 'Guests taking part in the ceremonial lamp lighting',
  },
  {
    id: 'opening-address-01',
    src: '/images/conference-gallery/opening-address-01.jpeg',
    section: 'Opening ceremony',
    title: 'Welcome address',
    alt: 'Conference representative delivering a welcome address at the podium',
  },
  {
    id: 'opening-address-02',
    src: '/images/conference-gallery/opening-address-02.jpeg',
    section: 'Opening ceremony',
    title: 'Opening address',
    alt: 'Conference speaker addressing the audience from the podium',
  },
  {
    id: 'opening-address-03',
    src: '/images/conference-gallery/opening-address-03.jpeg',
    section: 'Opening ceremony',
    title: 'Address to the delegates',
    alt: 'Speaker addressing delegates from the conference podium',
  },
  {
    id: 'opening-address-04',
    src: '/images/conference-gallery/opening-address-04.jpeg',
    section: 'Opening ceremony',
    title: 'Opening programme address',
    alt: 'Speaker delivering an address during the opening programme',
  },
  {
    id: 'opening-address-05',
    src: '/images/conference-gallery/opening-address-05.jpeg',
    section: 'Opening ceremony',
    title: 'Opening programme address',
    alt: 'Speaker delivering an address during the conference opening',
  },
  {
    id: 'opening-address-06',
    src: '/images/conference-gallery/opening-address-06.jpeg',
    section: 'Opening ceremony',
    title: 'Conference address',
    alt: 'Speaker delivering a conference address at the podium',
  },
  {
    id: 'co-hosted-address',
    src: '/images/conference-gallery/co-hosted-address.jpeg',
    section: 'Opening ceremony',
    title: 'Shared welcome address',
    alt: 'Two conference representatives speaking together at the podium',
  },
  {
    id: 'closing-address',
    src: '/images/conference-gallery/closing-address.jpeg',
    section: 'Opening ceremony',
    title: 'Address from the conference team',
    alt: 'Two conference representatives speaking at a podium',
  },
  {
    id: 'lamp-lighting-02',
    src: '/images/conference-gallery/lamp-lighting-02.jpeg',
    section: 'Opening ceremony',
    title: 'Ceremonial lamp lighting',
    alt: 'Guests gathered around the ceremonial lamp during the opening',
  },
  {
    id: 'lamp-lighting-03',
    src: '/images/conference-gallery/lamp-lighting-03.jpeg',
    section: 'Opening ceremony',
    title: 'Lamp lighting with the audience',
    alt: 'Guests lighting the ceremonial lamp with the audience seated behind them',
  },
  {
    id: 'felicitation-plant-01',
    src: '/images/conference-gallery/felicitation-plant-01.jpeg',
    section: 'Felicitation and recognition',
    title: 'Felicitation ceremony',
    alt: 'Conference guests presenting a plant during the felicitation ceremony',
  },
  {
    id: 'felicitation-plant-02',
    src: '/images/conference-gallery/felicitation-plant-02.jpeg',
    section: 'Felicitation and recognition',
    title: 'Felicitation ceremony',
    alt: 'Conference guests presenting a plant to an invited guest',
  },
  {
    id: 'felicitation-plant-03',
    src: '/images/conference-gallery/felicitation-plant-03.jpeg',
    section: 'Felicitation and recognition',
    title: 'Welcoming an invited guest',
    alt: 'An invited guest receiving a plant during ICCISD-2026',
  },
  {
    id: 'felicitation-plant-04',
    src: '/images/conference-gallery/felicitation-plant-04.jpeg',
    section: 'Felicitation and recognition',
    title: 'Felicitation ceremony',
    alt: 'Conference representatives presenting a plant during the ceremony',
  },
  {
    id: 'recognition-plaque',
    src: '/images/conference-gallery/recognition-plaque.jpeg',
    section: 'Felicitation and recognition',
    title: 'Presentation of a memento',
    alt: 'Conference representatives presenting a recognition plaque',
  },
  {
    id: 'certificate-presentation',
    src: '/images/conference-gallery/certificate-presentation.jpeg',
    section: 'Felicitation and recognition',
    title: 'Certificate presentation',
    alt: 'Conference representatives presenting a framed certificate',
  },
  {
    id: 'team-felicitation',
    src: '/images/conference-gallery/team-felicitation.jpeg',
    section: 'Felicitation and recognition',
    title: 'Recognition with the organising team',
    alt: 'Conference representatives gathered during a recognition ceremony',
  },
  {
    id: 'stage-conversation',
    src: '/images/conference-gallery/stage-conversation.jpeg',
    section: 'People and connections',
    title: 'A moment between sessions',
    alt: 'Conference guests seated together during the programme',
  },
  {
    id: 'organising-team',
    src: '/images/conference-gallery/organising-team.jpeg',
    section: 'People and connections',
    title: 'The organising team',
    alt: 'ICCISD-2026 organising team gathered in the conference room',
  },
  {
    id: 'team-certificate-01',
    src: '/images/conference-gallery/team-certificate-01.jpeg',
    section: 'People and connections',
    title: 'Team photograph after recognition',
    alt: 'Conference team members gathered after a certificate presentation',
  },
  {
    id: 'team-certificate-02',
    src: '/images/conference-gallery/team-certificate-02.jpeg',
    section: 'People and connections',
    title: 'Conference team gathering',
    alt: 'Conference representatives gathered around an ICCISD-2026 display',
  },
];

export const gallerySections = [
  {
    id: 'opening-ceremony',
    label: 'Opening ceremony',
    description: 'Welcome addresses, the ceremonial lamp lighting, and the first moments on stage.',
  },
  {
    id: 'felicitation-recognition',
    label: 'Felicitation and recognition',
    description: 'Plants, certificates, and mementos shared with the conference guests.',
  },
  {
    id: 'people-connections',
    label: 'People and connections',
    description: 'The conversations and group moments that made the conference feel shared.',
  },
];

export const galleryHighlights = conferenceGallery.filter((photo) => photo.featured);

export const homeGalleryHighlights = [
  conferenceGallery.find((photo) => photo.id === 'stage-group-panel'),
  conferenceGallery.find((photo) => photo.id === 'souvenir-release-stage'),
  conferenceGallery.find((photo) => photo.id === 'lamp-lighting-01'),
];
